### ISSUE TITLE
Please Update C2 ADMOB PLUS PRO for Android SDK 33

### ISSUE THREAD

**Issue by rifaldi** [EMI-INDO/c3addon-bug#1]
Since updating Cordova12 and SDK 33 build apk in Android Studio, ads no longer appear, please fix it, thank you

**Comment by ghost** [comment]
@rifaldi 

I will update it this month

**Comment by ghost** [comment]
@rifaldi 

Plugin updated

https://www.construct.net/en/game-assets/addons/c2-admob-plus-pro-1099

`remove old plugins`
`remove platform`

`cordova plugin add community-admob-plus-cordova --save --variable APP_ID_ANDROID=ca-app-pub-3944~3347511713`
`add platform`

build.....


### NOTE release

![new plugin id package](https://github.com/EMI-INDO/c3addon-bug/assets/39442895/b2326829-7345-4f1f-8fd8-3f50d098913b)

**Comment by rifaldi** [comment]
Wow... it works, and now it displays ads, thank you very much

**Comment by rifaldi** [comment]
> emi415064
Wow it works, and now it displays ads, thank you very much

**Comment by EMI-INDO** [comment]
fix
