### ISSUE TITLE
ADMOB PLUS PRO (update)

### ISSUE THREAD

**Issue by eltonnobrega** [EMI-INDO/c3addon-bug#11]
Hi, how are you?
You could add a consent_Status variable and put in a try block so that the consentStatus function always has a return. Because when the device is disconnected from the internet or when the internet connection goes down, the addon behaves strangely.

	this.consent_Status = "";
	const consentStatus = async() => {
                try
                {
                    const ss = await consent.getConsentStatus()
                    this.consent_Status = ss;
	                if (ss == consent.ConsentStatus.Unknown)
	                {
	                    self.Trigger(self.EMI_INDO.Statusunknown)
	                    self.debug_log = ('Unknown consent status')
	
	                }
	                else if (ss == consent.ConsentStatus.Required)
	                {
	                    await consent.requestInfoUpdate()
	                    self.Trigger(self.EMI_INDO.Statusrequired);
	                    self.debug_log = ('User consent required but not yet obtained.')
	
	                }
	                else if (ss == consent.ConsentStatus.NotRequired)
	                {
	                    self.Trigger(self.EMI_INDO.Statusnot_Required);
	                    self.debug_log = ('User consent not required. For example, the user is not in the EEA or the UK.');
	
	                }
	                else if (ss == consent.ConsentStatus.Obtained)
	                {
	                    self.Trigger(self.EMI_INDO.StatusObtained);
	                    self.debug_log = ('User consent was already obtained.');
	
	                }
	                else
	                {
	                    this.consent_Status = consent.ConsentStatus.Unknown;
	                    self.Trigger(self.EMI_INDO.Statusunknown)
	                    self.debug_log = ('Unknown condition consent status')
	                }
                    
                }
                catch (err)
                {
                	this.consent_Status = consent.ConsentStatus.Unknown;
                    self.Trigger(self.EMI_INDO.StatusError)
                    self.debug_log = (JSON.stringify('Error getConsentStatus :' + err))

                }

            };

**Comment by EMI-INDO** [comment]
I'll try and test it later

**Comment by EMI-INDO** [comment]
> Hai apa kabar?
> Anda dapat menambahkan variabel consent_Status dan memasukkan blok try sehingga fungsi consentStatus selalu kembali. Karena ketika perangkat terputus dari internet atau ketika koneksi internet mati, addon berperilaku aneh.
> 
> 
> this.consent_Status = "";
> const consentStatus = async() => {
>             try
>             {
>                 const ss = await consent.getConsentStatus()
>                 this.consent_Status = ss;
>                 if (ss == consent.ConsentStatus.Unknown)  
>                 {
>                     self.Trigger(self.EMI_INDO.Statusunknown)
>                     self.debug_log = ('Unknown consent status') 
> 
>                 }
>                 else if (ss == consent.ConsentStatus.Required)
>                 {
>                     await consent.requestInfoUpdate()
>                     self.Trigger(self.EMI_INDO.Statusrequired);
>                     self.debug_log = ('User consent required but not yet obtained.') 
> 
>                 }
>                 else if (ss == consent.ConsentStatus.NotRequired)
>                 {
>                     self.Trigger(self.EMI_INDO.Statusnot_Required);
>                     self.debug_log = ('User consent not required. For example, the user is not in the EEA or the UK.');  
> 
>                 }
>                 else if (ss == consent.ConsentStatus.Obtained)
>                 {
>                     self.Trigger(self.EMI_INDO.StatusObtained);
>                     self.debug_log = ('User consent was already obtained.'); 
> 
>                 }
>                 else
>                 {
>                     this.consent_Status = consent.ConsentStatus.Unknown;
>                     self.Trigger(self.EMI_INDO.Statusunknown)
>                     self.debug_log = ('Unknown condition consent status')
>                 }
>                 
>             }
>             catch (err)
>             {
>             	this.consent_Status = consent.ConsentStatus.Unknown;
>                 self.Trigger(self.EMI_INDO.StatusError)
>                 self.debug_log = (JSON.stringify('Error getConsentStatus :' + err))
> 
>             }
> 
>         };
>

Can you explain your problem in more detail?


**it just returns the value 0 or 1 or 2 or 3**

self.debug_log only translates from numbers to strings so it can be understood

self.debug_log = ('Unknown consent status')      === this result 0
self.debug_log = ('User consent required but not yet obtained.')       === this result 1
self.debug_log = ('User consent not required. For example, the user is not in the EEA or the UK.');       === this result 2
self.debug_log = ('User consent was already obtained.');        === this result 3


https://github.com/admob-plus/admob-plus/blob/76557eaf95905e1012a2084383c4bb34bcf05ecd/packages/cordova-consent/ts/generated.ts

**Comment by eltonnobrega** [comment]
In my game I wait for one of the values (0 or 1 or 2 or 3) of consent before proceeding. When I receive the value I continue the game. But when there is no internet the game does not continue because no value is returned. I believe that an exception must occur when there is no internet and the method is called.

![code](https://user-images.githubusercontent.com/2957278/134777909-6e71cd9c-a831-45bb-b739-50accef940bc.png)

**Comment by EMI-INDO** [comment]
I've made it, it will return response 0 or 1 or 2 or 3

Does it mean like this?

![2021-09-26_000851](https://user-images.githubusercontent.com/78555833/134780312-8c736994-96e1-4da0-afeb-0926c0bd9a87.png)

**Comment by eltonnobrega** [comment]
Excellent. Thanks.

**Comment by EMI-INDO** [comment]
maybe I'll release it tomorrow, right now I don't have time.

**Comment by EMI-INDO** [comment]
![2021-09-27_010115](https://user-images.githubusercontent.com/78555833/134818960-83ee6af4-a184-4345-b5e1-2d801af597ed.png)

**Comment by EMI-INDO** [comment]
@eltonnobrega 

### is this mediation plugin compatible with admob-plus-cordova ?

cordova_admob_mediation_applovin@1.0.1
cordova_admob_mediation_ironsource@1.0.0
cordova_admob_mediation_unityads@1.0.0

**Comment by eltonnobrega** [comment]
Yes, they are compatible with admob-plus-cordova.
It's an attempt, I'm meeting cordova now.
I just add the necessary libraries:
https://developers.google.com/admob/android/mediate#mediation_picker

AppLovin should run smoothly
https://developers.google.com/admob/android/mediation/applovin#step_4_additional_code_required

Unity ads should work smoothly
https://developers.google.com/admob/android/mediation/unity#step_4_additional_code_required

IronSource I must add more code
https://developers.google.com/admob/android/mediation/ironsource#step_4_additional_code_required

I didn't add the code for EU consent and GDPR in any of them either.
https://developers.google.com/admob/android/mediation/applovin#eu_consent_and_gdpr
https://developers.google.com/admob/android/mediation/unity#eu_consent_and_gdpr
https://developers.google.com/admob/android/mediation/ironsource#eu_consent_and_gdpr

[admobmediationapplovin_1_0_1_0.zip](https://github.com/EMI-INDO/c3addon-bug/files/7240136/admobmediationapplovin_1_0_1_0.zip)

**Comment by OBMStudioz** [comment]
![Capture](https://user-images.githubusercontent.com/95506419/144701796-707b0719-8341-489b-881e-0069cc6c22ed.PNG)
The properties section is not showing i have the version 2.0.0 of Admob Plus Pro please assist me

**Comment by EMI-INDO** [comment]
> ![Capture](https://user-images.githubusercontent.com/95506419/144701796-707b0719-8341-489b-881e-0069cc6c22ed.PNG) The properties section is not showing i have the version 2.0.0 of Admob Plus Pro please assist me



duplicate https://github.com/EMI-INDO/c3addon-bug/issues/14
