### ISSUE TITLE
FirebaseStartUp plugin working?

### ISSUE THREAD

**Issue by xdronx** [EMI-INDO/c3addon-bug#12]
Is the FirebaseStartUp plugin working?

I have installed Firebase StartUp plugin, after exporting to android, the game does not start.

a gray window opens
http://joxi.ru/EA4GZlXCvNnK52

tested on CONSTRUCT 3 R268 R260  R270
  

http://joxi.ru/YmEd0w9tBzv9gr
http://joxi.ru/V2VJgwdU8JNY82

P. S. Errors are possible as translated via Google Translate

**Comment by HAMEVG** [comment]
Hello,

I have the exact same problem (I bought the plugin this afternoon).

After having added the plugin, the app (android) opens on a grey screen and then does not respond.

**Comment by HAMEVG** [comment]
Hi EMI-INDO,

Do you have a solution to this problem (application blocked on a grey screen at startup on Android)? Or do you plan to do something about it? 

What? When???

The plugin seems to be exactly what I need but I need to know quickly what you will do. 

Thanks in advance.

**Comment by EMI-INDO** [comment]
@xdronx @HAMEVG 

update the plugin in any store you buy it


![FIX](https://user-images.githubusercontent.com/78555833/140532066-9dd2253e-99b7-43b5-a504-58fe30477081.png)
