### ISSUE TITLE
Ultimate Mediation

### ISSUE THREAD

**Issue by SouthernGames** [EMI-INDO/c3addon-bug#13]
Hi
I bought ultimate mediation on the store of C3, but i didn't understood how it works, i have created an account on adcolony and tapdaq, but i haven't understood how totally implement the addon on my app, can u make a step by step tutorial or write a tutorial here? thank you so much

**Comment by emi415064** [comment]
Use cordova cli, Follow all documentation.

https://www.construct.net/en/make-games/addons/503/ultimate-mediation-ads-basic/documentation

**Comment by SouthernGames** [comment]
how i can ad the gdpr consent window?

**Comment by SouthernGames** [comment]
> Use cordova cli, Follow all documentation.
> 
> https://www.construct.net/en/make-games/addons/503/ultimate-mediation-ads-basic/documentation

how i can add the gdpr consent window?
