### ISSUE TITLE
Admob Plus Pro issues in construct 3

### ISSUE THREAD

**Issue by OBMStudioz** [EMI-INDO/c3addon-bug#14]
![Capture](https://user-images.githubusercontent.com/95506419/144678962-ecabcdd6-5b6d-42a7-9194-b1f0011ca775.PNG)
The properties section is not showing i have the version 2.0.0 of Admob Plus Pro. I bought the plugin this week

**Comment by emi415064** [comment]
What do you mean by 2.0.0? It's a released version of addon.

![addon](https://user-images.githubusercontent.com/39442895/144714210-3efc1d27-9d5e-4218-92a3-9040738cff2c.png)

**Comment by OBMStudioz** [comment]
> What do you mean by 2.0.0? It's a released version of addon.
> 
> ![addon](https://user-images.githubusercontent.com/39442895/144714210-3efc1d27-9d5e-4218-92a3-9040738cff2c.png)

Yes i bought the version 2.0.0.0 but the property section is not appearing so i can choose test mode

**Comment by EMI-INDO** [comment]
@OBMStudioz 

Whatever your problem, explain it as clearly as possible.
