### ISSUE TITLE
FIREBASE ANALYTICS C3 Plugin Black Screen

### ISSUE THREAD

**Issue by KdomoGames** [EMI-INDO/c3addon-bug#18]
Hello!

I have an issue with this plugin: https://www.construct.net/en/game-assets/addons/firebase-analytics-403
I follow the video instructions and I can run the game on preview (in browser) but for android it gives me a black screen and the games doesn't initialize.

**Comment by EMI-INDO** [comment]
I will fix it

**Comment by jE-KI** [comment]
![2022-06-29_023024](https://user-images.githubusercontent.com/108358802/176269385-07cd5d23-beda-405f-bf49-d5248fc83abb.png)

**Comment by EMI-INDO** [comment]
![2022-06-29_023024](https://user-images.githubusercontent.com/78555833/176269667-7e375194-d592-4ba7-8cec-3c00208e48f1.png)

**Comment by KdomoGames** [comment]
![image](https://user-images.githubusercontent.com/106527689/177032048-58764303-06a6-497d-928d-ac872121065a.png)
those are the options I see

**Comment by EMI-INDO** [comment]
Are you using the free version of the plugin or the paid version?

**Comment by KdomoGames** [comment]
Yes, sorry I uploaded the wrong asset! 
![image](https://user-images.githubusercontent.com/106527689/177032839-31c8c773-3297-4282-abc8-2fd363c7d242.png)
Now it's working!
I have a doubt. In the past I got black screen because those values were wrong (the ones by value in the plugin). If I have a live version of the game with the plugin may I get the black screen again if I need to change them again?...

**Comment by EMI-INDO** [comment]
@KdomoGames 

yes keep using FirebaseStartUp to change the value if there is a problem.

**Comment by EMI-INDO** [comment]
@KdomoGames 

Is it normal now?

**Comment by KdomoGames** [comment]
Now it works, but I'm worried at some points the users will get black sreen on the live version, to change values I have to create a diff build and upload it to google, which takes about 2 days to approve...

**Comment by EMI-INDO** [comment]
I will fix some bugs in the code later.
