### ISSUE TITLE
[bug or no?] In the Applovin plugin, rewards and interstitial ads can only be displayed once.

### ISSUE THREAD

**Issue by rifaldi** [EMI-INDO/c3addon-bug#2]
Hello... I would like to inquire about the Construct 3 APPLOVIN plugin. It seems that the response for showing reward and interstitial ads can only happen once. To make them appear again, I have to either restart the layout or switch to another layout.
 Ideally, reward ads should be displayable without having to reload the layout first. Is there a solution to this issue? Thank you.

**Comment by ghost** [comment]
@rifaldi 

On rewarded completed = load rewarded ad

**Comment by rifaldi** [comment]
> On rewarded completed

There is no 'On rewarded completed' option for rewards, is there a suitable option?
![ScreenShot_20231111223851](https://github.com/EMI-INDO/c3addon-bug/assets/5943715/b974ac5c-176a-4ec1-ab93-8af51d72bdde)

**Comment by ghost** [comment]
@rifaldi 

Yes
 On Rewarded Ad Received = load rewarded ad

**Comment by rifaldi** [comment]
> load rewarded ad

I have tried it after On Rewarded Ad Received, but the ad still won't load. I have to click or touch the button to trigger the rewarded ad load after the ad is displayed first. Is this a bug?

**Comment by rifaldi** [comment]
I found the solution because the loading process cannot be done with a single trigger. I use text responses like this, and if it successfully loads, the text changes, and there is no need to load again until the text is specified
![ScreenShot_20231112233839](https://github.com/EMI-INDO/c3addon-bug/assets/5943715/53698bf7-c369-4077-acfe-ed4202cf43a7)

**Comment by ghost** [comment]
@rifaldi 

I'll check it later.

**Comment by EMI-INDO** [comment]
New release v1.0.0.9

https://www.construct.net/en/game-assets/addons/applovin-max-ads-1847
