### ISSUE TITLE
Consent

### ISSUE THREAD

**Issue by fredriksthlm** [EMI-INDO/c3addon-bug#2]
Does this plugin still use the old consent fron AdmobPlus, which uses the old legacy EU consent?

From the admob Plus I can see they changed into the new UMP. But it seems that you cannot get it to work? So just to be clear, is this plugin totally up to date with the latest Admob Plus versions, both admob and consent?

If this is not compliant you must clearly state this.

The ACEs must be fully compliant to the new consent and admob versions. are they?

**Comment by EMI-INDO** [comment]
@fredriksthlm 

### Which addon?

Include an addon link

**Comment by fredriksthlm** [comment]
the c3 addon you sell in the scirra store.. :)

are you on construct discord?

**Comment by EMI-INDO** [comment]
I didn't make a discord

SDK approval is always changing

first alpha: @alpha 0 - 11
first beta: @beta 0 - 3

### each new alpha and beta release, the code will be changed

20/03/2021 SDK fully released v1.0.0

Cordova consent SDK does not work

**Comment by EMI-INDO** [comment]
![ttt](https://user-images.githubusercontent.com/78555833/112203412-17829d00-8c45-11eb-90f2-2a454257323d.png)

**Comment by EMI-INDO** [comment]
it will work if it returns to version @0.19.0 ( 2020 )

cordova-plugin-consent@0.19.0

I will make it

**Comment by fredriksthlm** [comment]
Thats a very bad idea.

I can just say that:

admob-plus-cordova@1.0.1  uses Google UMP
admob-plus-cordova@0.19.0 uses Google EU Consent

So you say that you still will use the old EU consent still? You have not got the UMP to work? The ump is a totally new SDK, and it require you to create Funding Choices to work. Have you tried all this?

The old consent is deprecated and should not be used, at all.

**Comment by EMI-INDO** [comment]
sorry if I am wrong.

I am currently still learning to write code,
I'll try to make it work,

If someone has bought a plugin that I created, it doesn't work, and I can't fix it,
They are right to ask for a full refund.

**Comment by fredriksthlm** [comment]
Can I reach out to you? join the Construct discord server if you want
https://discord.gg/DXB8xMnU

Just wanted to share with you: That if you update and use the latest admob-plus-consent , you must set up Funding Choices in you Admob console. The new consent works very different from the old one. So to get it to work you must set it up first. Read more in Google ump setup documentation. And see in your Admob console.

Your code might be all fine!

**Comment by EMI-INDO** [comment]
### I am a fool, I can't speak English.
_I used google translate, to reply to this message._

I am ashamed to join, surely many people will laugh at me.

**Comment by fredriksthlm** [comment]
No man, it's alright. Everyone will be friendly.
But it would be nice if you joined since the plugin needs to comply with the latest requirements and it is easier to discuss on a live chat.

Regardless, good luck! You can look into the Google documentation.

**Comment by EMI-INDO** [comment]
![Screenshot_2021-03-24-17-05-33-275_com discord](https://user-images.githubusercontent.com/78555833/112292011-3e7fb400-8cc3-11eb-8736-9fc0b9ee0447.jpg)


Have I joined?

Cannot change Indonesian there
