### ISSUE TITLE
does not work. what should I do

### ISSUE THREAD

**Issue by Ivascuk** [EMI-INDO/c3addon-bug#3]
![Screenshot_2023-11-15-22-04-54-728_com android chrome](https://github.com/EMI-INDO/c3addon-bug/assets/150963215/927dc5ad-cc49-4ace-9ef6-45e860678d5a)

**Comment by ghost** [comment]
@Ivascuk 

You didn't say what plugin it was.

It's not clear what you mean.
Say clearly, plugin name and plugin source link..

**Comment by Ivascuk** [comment]
@EMI-INDO
ADMOB PLUS PRO
https://www.construct.net/en/game-assets/addons/admob-plus-pro-768
