### ISSUE TITLE
set up Tracking Authorization Status ios 14

### ISSUE THREAD

**Issue by sarawut985** [EMI-INDO/c3addon-bug#5]
Hi, I bought the ADMOB PLUS PRO plugin (Construct 3). I would like to know how to set up (Tracking Authorization Status ios 14)
could you make a guide?

**Comment by sarawut985** [comment]
I don't understand. Can you do a video tutorial?

**Comment by EMI-INDO** [comment]
> I don't understand. Can you do a video tutorial?

https://www.youtube.com/watch?v=H95BOh-9wGY

### call Tracking Authorization before the ad appears
**whatever the results show ads**

![IDFA](https://user-images.githubusercontent.com/78555833/118371294-2860e680-b5d6-11eb-9217-3a54a63eb4f3.png)

**Comment by EMI-INDO** [comment]
![track-2](https://user-images.githubusercontent.com/78555833/118371452-ebe1ba80-b5d6-11eb-95cf-15e4495bba37.png)
