### ISSUE TITLE
APPLOVIN requires using GDPR, How do I display the consent pop up message for GDPR?

### ISSUE THREAD

**Issue by rifaldi** [EMI-INDO/c3addon-bug#5]
because of the new policy, APPLOVIN requires using GDPR. How do I display PopUp consent for GDPR in the APPLOVIN plugin? Thank You

![ScreenShot_20231231113905](https://github.com/EMI-INDO/c3addon-bug/assets/5943715/c6ef8fed-bf6c-49a1-b475-ccca2288fbf2)

**Comment by EMI-INDO** [comment]
@rifaldi 

Wait for the next release, it's still under review.
https://github.com/Scirra/Construct-bugs/issues/7677

**Comment by rifaldi** [comment]
> @rifaldi
> 
> Wait for the next release, it's still under review. [Scirra/Construct-bugs#7677](https://github.com/Scirra/Construct-bugs/issues/7677)

yeah thank you I will wait for further good news

**Comment by EMI-INDO** [comment]
@rifaldi 

New release v1.0.0.9
https://www.construct.net/en/game-assets/addons/applovin-max-ads-1847
