### ISSUE TITLE
Black Screen After Update Applovin Release 1.0.0.9

### ISSUE THREAD

**Issue by rifaldi** [EMI-INDO/c3addon-bug#6]
hello, I would like to inform  there is an all black screen bug and the ad is not successfully displayed, when I use the ad call with on start of layout then I build the apk the results will be all black, but if I call (load) the ad via the button it is not black but the ad is not called is there something wrong or is this a bug?

![ScreenShot_20240108112411](https://github.com/EMI-INDO/c3addon-bug/assets/5943715/e49f2f4f-8848-4c3c-8e6a-e11c30a28b9a)

The build result when calling an ad at the start of layout will be black
![WhatsApp Image 2024-01-08 at 11 25 47](https://github.com/EMI-INDO/c3addon-bug/assets/5943715/72f41730-a9ee-4cf4-be2d-f83b4dbbbbb4)

**Comment by EMI-INDO** [comment]
@rifaldi 

- fix new release v1.0.1.9
https://www.construct.net/en/game-assets/addons/applovin-max-ads-1847

- fix bug: black screen
- new example c3p load ads

**Comment by rifaldi** [comment]
> @rifaldi
> 
> * fix new release v1.0.1.9
>   https://www.construct.net/en/game-assets/addons/applovin-max-ads-1847
> * fix bug: black screen
> * new example c3p load ads

After updating to 1.0.1.9 the black screen has been fixed and advertisements can be displayed, thank you to Dev EMI INDO for responding quickly :)

  but there is one more question, how to display GDPR consent? I have set it on start of layout/ via the button to display consent (Show Consent Options) but the results still don't appear to display consent. Is there something wrong or is there something else that is needed? I've seen that in the Applovin account there is no menu for setting up GDPR like AdMob, thank you

**Comment by EMI-INDO** [comment]
@rifaldi 

- VIDEO Enabling Google UMP: https://drive.google.com/file/d/1aD7kdufE1A_Q4fHMRJU7j5V2ob_ZTRMF/view

https://dash.applovin.com/documentation/mediation/android/getting-started/terms-and-privacy-policy-flow
https://dash.applovin.com/documentation/mediation/android/mediation-adapters?network=ADMOB_NETWORK

**Comment by sialifecom1234** [comment]
It's not there, where can I get it?
![Screenshot_20240110-101804_Drive](https://github.com/EMI-INDO/c3addon-bug/assets/133274841/01b90834-aca1-47c5-9d52-285a831eda6b)

**Comment by sialifecom1234** [comment]
this screenshot is from your video. I probably need to remove the plugin from the project and install it again, I’ll try it in the evening
