### ISSUE TITLE
ADMOB PLUS PRO set banner to overlap the webview

### ISSUE THREAD

**Issue by Boulerzzz** [EMI-INDO/c3addon-bug#7]
Hi,

Could you add an option to make the banner overlap the webview? When the banner is loaded now it shift my content upward so it is problematic to align the UI properly.

Currently the plugin loads the banner in a "safe zone" with black background like this:
![banner_1](https://user-images.githubusercontent.com/34767801/119670996-0e2ed000-be42-11eb-8b57-eaa9117c0af8.PNG)

I need the banner to be loaded to overlap like this:
![banner_2](https://user-images.githubusercontent.com/34767801/119670989-0d963980-be42-11eb-9638-3b46a6091bbe.PNG)

I'm not sure how this works. Would it work if you added an option to set the offset to 0?
https://admob-plus.github.io/docs/cordova/ads/banner

Thank you!

**Comment by EMI-INDO** [comment]
its next release.
offset banner set.

**Comment by EMI-INDO** [comment]
![2021-05-29_024641](https://user-images.githubusercontent.com/78555833/120035169-5871a600-c028-11eb-8bb3-d0e84fc1f9fc.png)
