### ISSUE TITLE
Sdk facebook

### ISSUE THREAD

**Issue by Asdrubal1981** [EMI-INDO/c3addon-bug#8]
addon uses the sdk facebook 6.2.
the last sdk is 6.5
using sdk 6.2 causes the app to crash
any solution?
![Screenshot_20210622-104703~2](https://user-images.githubusercontent.com/86290919/122894161-3e856380-d347-11eb-8fdf-f43d987fe44d.png)

**Comment by EMI-INDO** [comment]
ok, currently the addon is still under review by the team, c3 build service
