### ISSUE TITLE
ADMOB PLUS PRO - Child-directed stetting

### ISSUE THREAD

**Issue by eltonnobrega** [EMI-INDO/c3addon-bug#9]
Hi, I bought ADMOB PLUS PRO recently. I have a question, my app is aimed at children and is on the google made for families program. Should I add Child-directed stetting at plugin startup or every time before an ad?
Option 1?
![d1](https://user-images.githubusercontent.com/2957278/123649326-0e830800-d800-11eb-8880-adb9450311a9.png)
Option 2?
![d2](https://user-images.githubusercontent.com/2957278/123649332-0f1b9e80-d800-11eb-9b09-592a790b31d3.png)

**Comment by eltonnobrega** [comment]
I found a better solution. You can configure it for individual apps in Admob.
![admob1](https://user-images.githubusercontent.com/2957278/123698787-e5309f00-d834-11eb-8a5b-942f1061e194.png)

**Comment by EMI-INDO** [comment]
![2021-07-04_234938](https://user-images.githubusercontent.com/78555833/124393056-ca719500-dd22-11eb-879f-e42676a81589.png)

**Comment by eltonnobrega** [comment]
@EMI-INDO , I had already seen the existence of the action. My question is whether it should be called at every ad display ads:
![1](https://user-images.githubusercontent.com/2957278/124464377-81ddca00-dd6a-11eb-95dc-95b52d05d48c.png)
![2](https://user-images.githubusercontent.com/2957278/124464384-83a78d80-dd6a-11eb-9e67-62092fecb7db.png)

Or just on On start Layout:
![3](https://user-images.githubusercontent.com/2957278/124464403-873b1480-dd6a-11eb-8833-b34f5789540f.png)
